version: '3.7'

networks:
  laravel:
    name: ${NETWORK_NAME:-laravel}

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:12.1
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
      LC_ALL: C.UTF-8
    networks:
      - laravel

  php:
    build: .
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-laravel-docker-compose.test}
    networks:
      - laravel

volumes:
  pgdata:
